name: Deploy To AWS

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:

  deploy-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
      - run: npm install
      - run: npm run build

      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with: 
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.KEYID }}
          AWS_ACCESS_ACCESS_KEY: ${{ secrets.ACCESS_KEY}}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'dist'

      - name: Invalidate Cloudfront
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
            DISTRIBUTION: ${{  secrets.DISTRUBUTION }}
            PATHS: '/*'
            AWS_ACCESS_KEY_ID: ${{ secrets.KEYID }}
            AWS_ACCESS_ACCESS_KEY: ${{ secrets.ACCESS_KEY}}
            AWS_REGION: 'us-east-1'
          
