name: Deploy Backend To AWS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  deploy-frontend:
    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Set up Python!
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python Requirements
        run: pip install -r requirements.txt

      - name: Install Python Requirements
        run: pip install -r requirements.txt